import { describe, expect, it } from 'vitest'
import {
  parseEntries,
  parseEntriesAsMap,
  renderEnvFile,
  upsertEnvText,
} from '../src/envfile'
import { serverKeySet, deliveryKeySet } from '../src/mapping'

describe('parseEntries', () => {
  it('skips comments and blanks and splits at the first =', () => {
    const text = [
      '# Generated header',
      'DATABASE_URL=postgresql://user:pass@host/db?sslmode=require',
      '',
      'JWT_SECRET=abc=def=ghi',
      '  CORS_ORIGINS=http://a.example.com ',
      '# not-an-entry',
    ].join('\n')
    const entries = parseEntries(text)
    expect(entries).toEqual([
      { key: 'DATABASE_URL', value: 'postgresql://user:pass@host/db?sslmode=require' },
      { key: 'JWT_SECRET', value: 'abc=def=ghi' },
      { key: 'CORS_ORIGINS', value: 'http://a.example.com' },
    ])
    expect(parseEntriesAsMap(text)['JWT_SECRET']).toBe('abc=def=ghi')
  })
})

describe('renderEnvFile', () => {
  const canonical = [
    ['JWT_SECRET', 'jwt-1'],
    ['DELIVERY_URL', ''],
  ] as const

  it('renders header + canonical entries for a fresh file', () => {
    const text = renderEnvFile(canonical)
    expect(text).toContain('# Generated by OpenVOD bootstrap')
    expect(text).toContain('JWT_SECRET=jwt-1')
    expect(text).toContain('DELIVERY_URL=')
  })

  it('preserves unknown keys from an existing file (force regeneration)', () => {
    const existing = [
      '# old comment',
      'JWT_SECRET=old-jwt',
      'GOOGLE_CLIENT_ID=abc',
      'SWEEP_ENABLED=true',
    ].join('\n')
    const text = renderEnvFile(canonical, existing, serverKeySet())
    expect(text).toContain('JWT_SECRET=jwt-1')
    expect(text).toContain('GOOGLE_CLIENT_ID=abc')
    expect(text).toContain('SWEEP_ENABLED=true')
    expect(text).not.toContain('old-jwt')
    expect(text).not.toContain('# old comment')
  })

  it('drops stale canonical keys that are not part of the new set', () => {
    const existing = ['LEGACY_KEY=1', 'JWT_SECRET=x'].join('\n')
    const text = renderEnvFile(canonical, existing, deliveryKeySet())
    expect(text).toContain('LEGACY_KEY=1')
    expect(text).not.toContain('JWT_SECRET=x')
  })
})

describe('upsertEnvText', () => {
  const original = [
    '# header',
    'JWT_SECRET=jwt-1',
    'MODAL_WEBHOOK_URL=',
    '',
    'GOOGLE_CLIENT_ID=keep',
  ].join('\n')

  it('replaces known keys in place and appends new ones at the end', () => {
    const updated = upsertEnvText(original, [
      ['MODAL_WEBHOOK_URL', 'https://ws--x.modal.run'],
      ['DELIVERY_URL', 'https://media.workers.dev'],
    ])
    expect(updated).toContain('MODAL_WEBHOOK_URL=https://ws--x.modal.run')
    expect(updated).toContain('DELIVERY_URL=https://media.workers.dev')
    expect(updated).toContain('GOOGLE_CLIENT_ID=keep')
    expect(updated).toContain('JWT_SECRET=jwt-1')
  })

  it('keeps a trailing comment block before appended keys', () => {
    const withTail = `${original}\n# tail guidance\n# more guidance`
    const updated = upsertEnvText(withTail, [['DELIVERY_URL', 'https://d.example.com']])
    expect(updated.indexOf('# tail guidance')).toBeLessThan(
      updated.indexOf('DELIVERY_URL=https://d.example.com'),
    )
    expect(updated).toContain('# more guidance')
  })
})
