#!/usr/bin/env bash
#
# OpenVOD interactive BYOK setup wizard (bash).
#
# Prompts for the credentials your deployment needs, writes
# server/.dev.vars (never overwrites an existing file without --force),
# and prints the remaining manual steps (Modal secrets, wrangler, buckets).
#
# Usage:
#   scripts/setup.sh            # interactive
#   scripts/setup.sh --check <api-url>   # also probe GET /health/config

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
TARGET="$REPO_ROOT/server/.dev.vars"
EXAMPLE="$REPO_ROOT/server/.dev.vars.example"
FORCE=0
CHECK_URL=""

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --check) CHECK_URL="${2:-}" ;;
  esac
done

if [[ -f "$TARGET" && "$FORCE" != "1" ]]; then
  echo "✋ $TARGET already exists. Re-run with --force to overwrite, or edit it directly."
  exit 1
fi
if [[ ! -f "$EXAMPLE" ]]; then
  echo "✋ Missing template: $EXAMPLE"
  exit 1
fi

echo
echo "┌─────────────────────────────────────────────┐"
echo "│  OpenVOD — bring-your-own-keys setup        │"
echo "└─────────────────────────────────────────────┘"
echo

read -rp "Cloudflare Account ID [ACCOUNT_ID]: " ACCOUNT_ID
read -rp "R2 Access Key ID [R2_ACCESS_KEY_ID]: " R2_ACCESS_KEY_ID
read -rsp "R2 Secret Access Key [R2_SECRET_ACCESS_KEY]: " R2_SECRET_ACCESS_KEY; echo
read -rp "Raw upload bucket name [RAW_BUCKET_NAME]: " RAW_BUCKET_NAME
read -rp "Transcoded bucket name [TRANSCODED_BUCKET_NAME]: " TRANSCODED_BUCKET_NAME
read -rp "Postgres connection URL [DATABASE_URL]: " DATABASE_URL
read -rp "Modal webhook URL [MODAL_WEBHOOK_URL]: " MODAL_WEBHOOK_URL
read -rsp "Transcode ingest secret (share with your Modal env) [TRANSCODE_INGEST_SECRET]: " TRANSCODE_INGEST_SECRET; echo
read -rp "Delivery base URL [DELIVERY_URL]: " DELIVERY_URL

# Generate secrets when blank
BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET:-$(openssl rand -hex 32)}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
INTERNAL_SWEEP_SECRET="${INTERNAL_SWEEP_SECRET:-$(openssl rand -hex 32)}"
BETTER_AUTH_URL="${BETTER_AUTH_URL:-http://localhost:8787}"
BACKEND_URL="${BACKEND_URL:-http://localhost:8787}"
FRONTEND_URL="${FRONTEND_URL:-http://localhost:3000}"

cat > "$TARGET" <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=$DATABASE_URL
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
BETTER_AUTH_URL=$BETTER_AUTH_URL
FRONTEND_URL=$FRONTEND_URL
BACKEND_URL=$BACKEND_URL
ACCOUNT_ID=$ACCOUNT_ID
R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
RAW_BUCKET_NAME=$RAW_BUCKET_NAME
TRANSCODED_BUCKET_NAME=$TRANSCODED_BUCKET_NAME
MODAL_WEBHOOK_URL=$MODAL_WEBHOOK_URL
TRANSCODE_INGEST_SECRET=$TRANSCODE_INGEST_SECRET
JWT_SECRET=$JWT_SECRET
DELIVERY_URL=$DELIVERY_URL
INTERNAL_SWEEP_SECRET=$INTERNAL_SWEEP_SECRET
EOF
echo "✅ Wrote $TARGET"

cat <<'EOF'

Next steps:
  1. Create the R2 buckets in Cloudflare and add the S3 CORS rule
     (see docs/quickstart / docs site).
  2. Deploy the transcoder to Modal and mirror the secrets there:
       cd transcoding
       modal secret create r2-creds      # R2_ACCOUNT_ID, R2_ACCESS_KEY_ID,
                                         # R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME
       modal secret create groq-creds    # GROQ_API_KEY (optional)
       modal deploy main.py
     Set ALLOWED_CALLBACK_HOSTS=<your-api-host> and
     ALLOWED_SOURCE_BUCKETS=<RAW_BUCKET_NAME> in the Modal environment.
  3. Push the database schema:
       pnpm db:push
  4. Run the API and delivery workers (see README quickstart) and set
     INTERNAL_SWEEP_SECRET as a secret on the API deployment.
EOF

if [[ -n "$CHECK_URL" ]]; then
  echo "→ Probing $CHECK_URL/health/config ..."
  curl -fsS "$CHECK_URL/health/config" && echo
fi
