#!/usr/bin/env bash
#
# OpenVOD interactive BYOK setup wizard (bash).
#
# Prompts for the credentials your deployment needs, writes
# server/.dev.vars (never overwrites an existing file without --force),
# mirrors JWT_SECRET into delivery/.dev.vars, and prints the remaining
# manual steps (Modal secrets, wrangler or compose, buckets).
#
# Usage:
#   scripts/setup.sh                      # interactive
#   scripts/setup.sh --force              # overwrite existing files
#   scripts/setup.sh --check <api-url>    # also probe GET /health/config

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
TARGET="$REPO_ROOT/server/.dev.vars"
DELIVERY_TARGET="$REPO_ROOT/delivery/.dev.vars"
EXAMPLE="$REPO_ROOT/server/.dev.vars.example"
FORCE=0
CHECK_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --check)
      CHECK_URL="${2:-}"
      if [[ -z "$CHECK_URL" ]]; then
        echo "✋ --check requires an API URL (e.g. http://localhost:8787)"
        exit 1
      fi
      shift 2
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [[ -f "$TARGET" && "$FORCE" != "1" ]]; then
  echo "✋ $TARGET already exists. Re-run with --force to overwrite, or edit it directly."
  exit 1
fi
if [[ ! -f "$EXAMPLE" ]]; then
  echo "✋ Missing template: $EXAMPLE"
  exit 1
fi

echo
echo "┌─────────────────────────────────────────────┐"
echo "│  OpenVOD — bring-your-own-keys setup        │"
echo "└─────────────────────────────────────────────┘"
echo

read -rp "API runtime — workers (Neon HTTP) or docker (pg driver) [workers]: " API_RUNTIME
API_RUNTIME="${API_RUNTIME:-workers}"
if [[ "$API_RUNTIME" == "docker" ]]; then
  DB_DRIVER="pg"
else
  DB_DRIVER="neon-http"
fi

read -rp "Cloudflare Account ID [ACCOUNT_ID]: " ACCOUNT_ID
read -rp "R2 Access Key ID [R2_ACCESS_KEY_ID]: " R2_ACCESS_KEY_ID
read -rsp "R2 Secret Access Key [R2_SECRET_ACCESS_KEY]: " R2_SECRET_ACCESS_KEY; echo
read -rp "Raw upload bucket name [RAW_BUCKET_NAME]: " RAW_BUCKET_NAME
read -rp "Transcoded bucket name [TRANSCODED_BUCKET_NAME]: " TRANSCODED_BUCKET_NAME
read -rp "Postgres connection URL [DATABASE_URL]: " DATABASE_URL
read -rp "Modal webhook URL [MODAL_WEBHOOK_URL]: " MODAL_WEBHOOK_URL
read -rsp "Transcode ingest secret (share with your Modal env) [TRANSCODE_INGEST_SECRET]: " TRANSCODE_INGEST_SECRET; echo
read -rp "Delivery worker base URL [DELIVERY_URL]: " DELIVERY_URL

# Generate secrets when blank
BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET:-$(openssl rand -hex 32)}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
INTERNAL_SWEEP_SECRET="${INTERNAL_SWEEP_SECRET:-$(openssl rand -hex 32)}"
BETTER_AUTH_URL="${BETTER_AUTH_URL:-http://localhost:8787}"
BACKEND_URL="${BACKEND_URL:-http://localhost:8787}"
FRONTEND_URL="${FRONTEND_URL:-http://localhost:3000}"

cat > "$TARGET" <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=$DATABASE_URL
DB_DRIVER=$DB_DRIVER
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
BETTER_AUTH_URL=$BETTER_AUTH_URL
FRONTEND_URL=$FRONTEND_URL
BACKEND_URL=$BACKEND_URL
ACCOUNT_ID=$ACCOUNT_ID
R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
RAW_BUCKET_NAME=$RAW_BUCKET_NAME
TRANSCODED_BUCKET_NAME=$TRANSCODED_BUCKET_NAME
MODAL_WEBHOOK_URL=$MODAL_WEBHOOK_URL
TRANSCODE_INGEST_SECRET=$TRANSCODE_INGEST_SECRET
JWT_SECRET=$JWT_SECRET
DELIVERY_URL=$DELIVERY_URL
INTERNAL_SWEEP_SECRET=$INTERNAL_SWEEP_SECRET
EOF
echo "✅ Wrote $TARGET"

if [[ -f "$DELIVERY_TARGET" && "$FORCE" != "1" ]]; then
  echo "✋ $DELIVERY_TARGET already exists — not overwriting. Ensure JWT_SECRET matches the API."
else
  cat > "$DELIVERY_TARGET" <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# MUST equal the API JWT_SECRET — playback tokens are minted there and verified here.
JWT_SECRET=$JWT_SECRET
DEFAULT_POLICY=public
DELIVERY_DEBUG=false
EOF
  echo "✅ Wrote $DELIVERY_TARGET (JWT_SECRET mirrored from the API)"
fi

cat <<EOF

Next steps:
  1. Create the R2 buckets in Cloudflare and add the S3 CORS rule
     (see docs/deploy.md / docs site).
  2. Deploy the transcoder to Modal and mirror the secrets there:
       cd transcoding
       modal secret create r2-creds      # R2_ACCOUNT_ID, R2_ACCESS_KEY_ID,
                                         # R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME
       modal secret create groq-creds    # GROQ_API_KEY (optional)
       modal deploy main.py
     Set ALLOWED_CALLBACK_HOSTS=<your-api-host> and
     ALLOWED_SOURCE_BUCKETS=<RAW_BUCKET_NAME> in the Modal environment.
  3. Push the database schema:
       pnpm db:push
EOF

if [[ "$API_RUNTIME" == "docker" ]]; then
  cat <<'EOF'
  4. Boot API + dashboard + Postgres:
       docker compose up -d
     Then deploy the Cloudflare *delivery* worker (required for playback):
       cd delivery && wrangler deploy
     Compose does not serve signed HLS/DASH.
EOF
else
  cat <<'EOF'
  4. Deploy the API and delivery workers:
       cd server && wrangler deploy
       cd ../delivery && wrangler deploy
     Add your own custom domain routes in each wrangler.jsonc after first deploy.
     Optional: enable the job sweeper cron (SWEEP_ENABLED=true + triggers.crons).
EOF
fi

cat <<'EOF'
  5. Set INTERNAL_SWEEP_SECRET as a secret on the API deployment.
     Docker/VPS: POST /api/internal/sweep on a cron.
EOF

if [[ -n "$CHECK_URL" ]]; then
  echo "→ Probing $CHECK_URL/health/config ..."
  curl -fsS "$CHECK_URL/health/config" && echo
fi
