"""Encoding seam: backends, capability probes and the fallback policy."""
from clipmux_transcoder.encoding.backends import (
    ALL_BACKENDS,
    BACKEND_CPU,
    BACKEND_NVENC,
    BACKEND_VAAPI,
    CPU_BACKEND,
    NVENC_BACKEND,
    VAAPI_BACKEND,
    EncoderBackend,
    RenderSpec,
    build_audio_command,
    build_video_command,
    backend_named,
    h264_level,
    keyframe_interval,
)
from clipmux_transcoder.encoding.probe import (
    CapabilityReport,
    ChainProbe,
    EncoderProbe,
    classify_probe_failure,
    detect_capabilities,
    parse_encoder_list,
    parse_hwaccels,
    preflight_source,
    probe_backend,
)
from clipmux_transcoder.encoding.selection import (
    BackendCandidate,
    FallbackState,
    describe_chain,
    select_chain,
)

__all__ = [
    "ALL_BACKENDS",
    "BACKEND_CPU",
    "BACKEND_NVENC",
    "BACKEND_VAAPI",
    "CPU_BACKEND",
    "NVENC_BACKEND",
    "VAAPI_BACKEND",
    "BackendCandidate",
    "CapabilityReport",
    "ChainProbe",
    "EncoderBackend",
    "EncoderProbe",
    "FallbackState",
    "RenderSpec",
    "backend_named",
    "build_audio_command",
    "build_video_command",
    "classify_probe_failure",
    "describe_chain",
    "detect_capabilities",
    "h264_level",
    "keyframe_interval",
    "parse_encoder_list",
    "parse_hwaccels",
    "preflight_source",
    "probe_backend",
    "select_chain",
]
