/**
 * .dev.vars parsing/rendering. Pure text functions here; the filesystem
 * helpers are deliberately small and keep secrets out of stdout.
 *
 * Format is the loose `KEY=VALUE` line format wrangler/.dev.vars accepts.
 * Values are written raw (URLs and secrets contain no spaces or quotes).
 */

import type { EnvEntry, EntryList } from './mapping'

export interface ParsedEntry {
  key: string
  value: string
}

/** Parse only real entries (skips comments and blanks). First '=' splits. */
export function parseEntries(text: string): ParsedEntry[] {
  const entries: ParsedEntry[] = []
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trimEnd()
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq <= 0) continue
    const key = line.slice(0, eq).trim()
    const value = line.slice(eq + 1)
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue
    entries.push({ key, value })
  }
  return entries
}

/** Map view of parseEntries() (last occurrence wins). */
export function parseEntriesAsMap(text: string): Record<string, string> {
  const map: Record<string, string> = {}
  for (const { key, value } of parseEntries(text)) map[key] = value
  return map
}

function renderHeader(): string {
  return '# Generated by OpenVOD bootstrap (scripts/bootstrap.sh) on ' +
    new Date().toISOString()
}

/**
 * Render a full env file: header + canonical entries + (when an existing file
 * is being regenerated with --force) any pre-existing entries whose keys are
 * not part of the canonical set (e.g. GOOGLE_CLIENT_ID, SWEEP_*), preserving
 * their original order so values are never lost.
 */
export function renderEnvFile(
  canonical: EntryList,
  existingText?: string,
  existingKeySet?: ReadonlySet<string>,
): string {
  const lines: string[] = [renderHeader(), '']

  for (const [key, value] of canonical) lines.push(`${key}=${value}`)

  if (existingText !== undefined && existingKeySet !== undefined) {
    const kept = parseEntries(existingText).filter(({ key }) => !existingKeySet.has(key))
    if (kept.length > 0) {
      lines.push('')
      for (const { key, value } of kept) lines.push(`${key}=${value}`)
    }
  }

  return lines.join('\n') + '\n'
}

/**
 * In-place upsert of entries into an existing env file text (used after
 * deploys to fill MODAL_WEBHOOK_URL/DELIVERY_URL/… without regenerating).
 * Preserves comments, blanks and unknown keys.
 */
export function upsertEnvText(text: string, updates: readonly EnvEntry[]): string {
  const updateByKey = new Map<string, string>()
  for (const [key, value] of updates) updateByKey.set(key, value)

  const lines = text.split(/\r?\n/)
  const touched = new Set<string>()
  const out: string[] = []
  let tailComment = ''
  for (const rawLine of lines) {
    const line = rawLine.trimEnd()
    const trimmed = line.trim()
    if (trimmed.startsWith('#') && out.length > 0 && !tailComment) {
      // Remember a trailing comment block so appends land after it.
      tailComment = tailComment ? tailComment + '\n' + line : line
      continue
    }
    if (trimmed === '') continue
    const eq = line.indexOf('=')
    const key = eq > 0 ? line.slice(0, eq).trim() : ''
    const replacement = updateByKey.get(key)
    if (replacement !== undefined) {
      out.push(`${key}=${replacement}`)
      touched.add(key)
      tailComment = ''
    } else {
      out.push(line)
    }
  }
  if (tailComment) out.push(tailComment)
  for (const [key, value] of updates) {
    if (!touched.has(key)) out.push(`${key}=${value}`)
  }
  return out.join('\n') + '\n'
}

/** Error thrown when a target env file exists and --force was not given. */
export class EnvFileExistsError extends Error {
  constructor(public readonly path: string) {
    super(`${path} already exists — re-run with --force to regenerate (unrelated keys are preserved)`)
    this.name = 'EnvFileExistsError'
  }
}
