/**
 * Cross-language contract: what the Python engine produces, and what the API
 * makes of it.
 *
 * The fixtures in `transcoding/tests/fixtures/completion_payloads.json` are
 * generated from the *real* engine (`python -m tests.contract_fixtures`), and a
 * Python test fails if they ever drift. This side asserts the other half: that
 * both payload shapes resolve to URLs a viewer can actually fetch.
 *
 * The regression this exists for produced a bug no single-language test could
 * see. The engine began returning output-relative paths; the API handles a Modal
 * callback with rebasing *off*, because a Modal worker writes to the legacy
 * `videos/<id>/` layout and its callback used to carry complete keys. Neither
 * side was wrong on its own, and every new Modal video was unplayable.
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { attemptPrefix, parseCompletionPayload } from '../../src/lib/lifecycleFinalize'

const HERE = dirname(fileURLToPath(import.meta.url))
const FIXTURE_PATH = join(
  HERE,
  '..',
  '..',
  '..',
  'transcoding',
  'tests',
  'fixtures',
  'completion_payloads.json',
)

type Fixtures = {
  meta: { videoId: string; attemptId: string; r2Prefix: string }
  modal: Record<string, unknown>
  agent: Record<string, unknown>
  mixedAgent: Record<string, unknown>
}

const fixtures = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as Fixtures
const DELIVERY = 'https://delivery.example.com'

describe('completion payload contract', () => {
  it('has fixtures generated by the real engine', () => {
    expect(fixtures.meta.note).toContain('contract_fixtures.py')
    expect(fixtures.modal).toBeTruthy()
    expect(fixtures.agent).toBeTruthy()
    expect(fixtures.mixedAgent).toBeTruthy()
  })

  describe('Modal callback (rebasing off)', () => {
    const parsed = parseCompletionPayload(fixtures.modal, {
      outputPrefix: null,
      deliveryBaseUrl: DELIVERY,
    })

    it('resolves a playlist URL that includes the video id', () => {
      // The regression: this was `https://delivery.example.com/playlist.m3u8`,
      // which is a 404 for every viewer while the job reports success.
      expect(parsed.hlsUrl).toBe(
        `${DELIVERY}/videos/${fixtures.meta.videoId}/playlist.m3u8`,
      )
    })

    it('resolves the poster and subtitle URLs the same way', () => {
      expect(parsed.thumbnailUrl).toBe(
        `${DELIVERY}/videos/${fixtures.meta.videoId}/poster.jpg`,
      )
      expect(parsed.subtitleUrl).toBe(
        `${DELIVERY}/videos/${fixtures.meta.videoId}/subtitles.vtt`,
      )
    })

    it('carries the duration and renditions the engine reported', () => {
      expect(parsed.duration).toBeCloseTo(61.4, 5)
      expect(parsed.resolutions).toEqual(['1080p'])
    })

    it('reports subtitles and chapters as completed', () => {
      expect(parsed.subtitleStatus).toBe('completed')
      expect(parsed.chaptersStatus).toBe('completed')
      expect(parsed.chapters?.[0]?.title).toBe('Introduction')
    })
  })

  describe('agent completion (rebasing on)', () => {
    const prefix = attemptPrefix(fixtures.meta.videoId, fixtures.meta.attemptId)
    const parsed = parseCompletionPayload(fixtures.agent, {
      outputPrefix: prefix,
      deliveryBaseUrl: DELIVERY,
    })

    it('re-bases the relative playlist path onto the attempt prefix', () => {
      expect(parsed.hlsUrl).toBe(`${DELIVERY}/${prefix}/playlist.m3u8`)
    })

    it('re-bases every artifact, not just the playlist', () => {
      expect(parsed.thumbnailUrl).toBe(`${DELIVERY}/${prefix}/poster.jpg`)
      expect(parsed.subtitleUrl).toBe(`${DELIVERY}/${prefix}/subtitles.vtt`)
    })

    it('never produces a URL outside the attempt prefix', () => {
      for (const url of [parsed.hlsUrl, parsed.thumbnailUrl, parsed.subtitleUrl]) {
        expect(url?.startsWith(`${DELIVERY}/${prefix}/`)).toBe(true)
      }
    })

    it('is not double-prefixed when the API also has the Modal prefix', () => {
      // Applying the Modal layout on top of the agent's relative paths would
      // produce `videos/<id>/videos/<id>/attempts/...`, which exists nowhere.
      expect(parsed.hlsUrl).not.toContain(`videos/${fixtures.meta.videoId}/videos/`)
    })
  })

  describe('mixed-backend agent completion', () => {
    const prefix = attemptPrefix(fixtures.meta.videoId, fixtures.meta.attemptId)
    const parsed = parseCompletionPayload(fixtures.mixedAgent, {
      outputPrefix: prefix,
      deliveryBaseUrl: DELIVERY,
    })
    const meta = JSON.parse(parsed.metadataJson) as Record<string, unknown>

    it('accepts a ladder the engine finished across two encoders', () => {
      // `mixed` is not an encoder: it says each rung carried its own fallback
      // state, so no single name describes the whole job. The API has to store
      // the literal rather than reject it or normalize it into a claim about an
      // encoder that never ran the whole ladder.
      expect(meta.backend).toBe('mixed')
      expect(parsed.resolutions).toEqual(['1080p', '720p'])
      expect(parsed.hlsUrl).toBe(`${DELIVERY}/${prefix}/playlist.m3u8`)
    })

    it('round-trips the per-rendition execution details', () => {
      // One rung on NVENC (with a software-decode hybrid attempt), one on CPU —
      // the whole reason the whole-job backend cannot answer "which encoder
      // produced this rung?".
      expect(meta.renditions).toEqual([
        {
          label: '1080p',
          width: 1920,
          height: 1080,
          bitrate: '5M',
          backend: 'nvenc',
          mode: 'hybrid',
          attempts: 2,
          seconds: 41.5,
          bytes: 66560,
        },
        {
          label: '720p',
          width: 1280,
          height: 720,
          bitrate: '3M',
          backend: 'cpu',
          mode: 'cpu',
          attempts: 1,
          seconds: 22.75,
          bytes: 30720,
        },
      ])
    })

    it('round-trips the toolchain that produced them', () => {
      expect(meta.toolchain).toEqual({
        engine: '1.1.0',
        ffmpeg: '9.0.1',
        planVersion: '2',
        shaka: '3.2.0',
      })
    })
  })

  describe('diagnostics are additive', () => {
    /** A fixture with the two new `processing` keys removed (older engine). */
    function withoutDiagnostics(fixture: Record<string, unknown>): Record<string, unknown> {
      const copy = JSON.parse(JSON.stringify(fixture)) as Record<string, unknown>
      const processing = copy.processing as Record<string, unknown>
      delete processing.renditions
      delete processing.toolchain
      return copy
    }

    it('parses an older engine payload without inventing empty keys', () => {
      // Backwards compatibility is the point: an engine that predates the
      // diagnostics sends neither key, and `renditions: []` on the video would
      // read as "this job had no renditions" — a claim the payload never made.
      const prefix = attemptPrefix(fixtures.meta.videoId, fixtures.meta.attemptId)
      const parsed = parseCompletionPayload(withoutDiagnostics(fixtures.agent), {
        outputPrefix: prefix,
        deliveryBaseUrl: DELIVERY,
      })
      const meta = JSON.parse(parsed.metadataJson) as Record<string, unknown>

      expect(meta).not.toHaveProperty('renditions')
      expect(meta).not.toHaveProperty('toolchain')
      // The existing keys keep their meaning, `backend` included.
      expect(meta.backend).toBe('cpu')
      expect(meta.plan_fingerprint).toBe('fingerprint-contract')
      expect(parsed.hlsUrl).toBe(`${DELIVERY}/${prefix}/playlist.m3u8`)
    })

    it('keeps only typed rendition fields and string-valued toolchain entries', () => {
      const payload = withoutDiagnostics(fixtures.agent)
      const processing = payload.processing as Record<string, unknown>
      processing.renditions = [
        'nope',
        null,
        { width: 1920 },
        { label: 42, backend: 'nvenc' },
        // A documented field with the wrong type stays typed (`null`), a scalar
        // field this build has never heard of is carried through for the next
        // engine version, and a nested object is dropped outright.
        { label: '1080p', width: 'wide', backend: 'cpu', decode_seconds: 4.2, nested: { a: 1 } },
      ]
      processing.toolchain = { ffmpeg: 9, shaka: '3.2.0' }

      const parsed = parseCompletionPayload(payload, {
        outputPrefix: null,
        deliveryBaseUrl: DELIVERY,
      })
      const meta = JSON.parse(parsed.metadataJson) as Record<string, unknown>

      expect(meta.renditions).toEqual([
        {
          label: '1080p',
          width: null,
          height: null,
          bitrate: null,
          backend: 'cpu',
          mode: null,
          attempts: null,
          seconds: null,
          bytes: null,
          decode_seconds: 4.2,
        },
      ])
      expect(meta.toolchain).toEqual({ shaka: '3.2.0' })
    })

    it('omits both keys when the diagnostics have nothing usable', () => {
      const payload = withoutDiagnostics(fixtures.agent)
      const processing = payload.processing as Record<string, unknown>
      processing.renditions = []
      processing.toolchain = 'ffmpeg 9.0.1'

      const parsed = parseCompletionPayload(payload, {
        outputPrefix: null,
        deliveryBaseUrl: DELIVERY,
      })
      const meta = JSON.parse(parsed.metadataJson) as Record<string, unknown>

      expect(meta).not.toHaveProperty('renditions')
      expect(meta).not.toHaveProperty('toolchain')
    })
  })

  describe('the two shapes differ only by prefix', () => {
    it('produces the same playback filename in both layouts', () => {
      const modal = parseCompletionPayload(fixtures.modal, {
        outputPrefix: null,
        deliveryBaseUrl: DELIVERY,
      })
      const agent = parseCompletionPayload(fixtures.agent, {
        outputPrefix: attemptPrefix(fixtures.meta.videoId, fixtures.meta.attemptId),
        deliveryBaseUrl: DELIVERY,
      })
      expect(modal.hlsUrl?.endsWith('/playlist.m3u8')).toBe(true)
      expect(agent.hlsUrl?.endsWith('/playlist.m3u8')).toBe(true)
      expect(modal.hlsUrl).not.toBe(agent.hlsUrl)
    })
  })
})
