/**
 * Cross-language contract: what the Python engine produces, and what the API
 * makes of it.
 *
 * The fixtures in `transcoding/tests/fixtures/completion_payloads.json` are
 * generated from the *real* engine (`python -m tests.contract_fixtures`), and a
 * Python test fails if they ever drift. This side asserts the other half: that
 * both payload shapes resolve to URLs a viewer can actually fetch.
 *
 * The regression this exists for produced a bug no single-language test could
 * see. The engine began returning output-relative paths; the API handles a Modal
 * callback with rebasing *off*, because a Modal worker writes to the legacy
 * `videos/<id>/` layout and its callback used to carry complete keys. Neither
 * side was wrong on its own, and every new Modal video was unplayable.
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { attemptPrefix, parseCompletionPayload } from '../../src/lib/lifecycleFinalize'

const HERE = dirname(fileURLToPath(import.meta.url))
const FIXTURE_PATH = join(
  HERE,
  '..',
  '..',
  '..',
  'transcoding',
  'tests',
  'fixtures',
  'completion_payloads.json',
)

type Fixtures = {
  meta: { videoId: string; attemptId: string; r2Prefix: string }
  modal: Record<string, unknown>
  agent: Record<string, unknown>
}

const fixtures = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as Fixtures
const DELIVERY = 'https://delivery.example.com'

describe('completion payload contract', () => {
  it('has fixtures generated by the real engine', () => {
    expect(fixtures.meta.note).toContain('contract_fixtures.py')
    expect(fixtures.modal).toBeTruthy()
    expect(fixtures.agent).toBeTruthy()
  })

  describe('Modal callback (rebasing off)', () => {
    const parsed = parseCompletionPayload(fixtures.modal, {
      outputPrefix: null,
      deliveryBaseUrl: DELIVERY,
    })

    it('resolves a playlist URL that includes the video id', () => {
      // The regression: this was `https://delivery.example.com/playlist.m3u8`,
      // which is a 404 for every viewer while the job reports success.
      expect(parsed.hlsUrl).toBe(
        `${DELIVERY}/videos/${fixtures.meta.videoId}/playlist.m3u8`,
      )
    })

    it('resolves the poster and subtitle URLs the same way', () => {
      expect(parsed.thumbnailUrl).toBe(
        `${DELIVERY}/videos/${fixtures.meta.videoId}/poster.jpg`,
      )
      expect(parsed.subtitleUrl).toBe(
        `${DELIVERY}/videos/${fixtures.meta.videoId}/subtitles.vtt`,
      )
    })

    it('carries the duration and renditions the engine reported', () => {
      expect(parsed.duration).toBeCloseTo(61.4, 5)
      expect(parsed.resolutions).toEqual(['1080p'])
    })

    it('reports subtitles and chapters as completed', () => {
      expect(parsed.subtitleStatus).toBe('completed')
      expect(parsed.chaptersStatus).toBe('completed')
      expect(parsed.chapters?.[0]?.title).toBe('Introduction')
    })
  })

  describe('agent completion (rebasing on)', () => {
    const prefix = attemptPrefix(fixtures.meta.videoId, fixtures.meta.attemptId)
    const parsed = parseCompletionPayload(fixtures.agent, {
      outputPrefix: prefix,
      deliveryBaseUrl: DELIVERY,
    })

    it('re-bases the relative playlist path onto the attempt prefix', () => {
      expect(parsed.hlsUrl).toBe(`${DELIVERY}/${prefix}/playlist.m3u8`)
    })

    it('re-bases every artifact, not just the playlist', () => {
      expect(parsed.thumbnailUrl).toBe(`${DELIVERY}/${prefix}/poster.jpg`)
      expect(parsed.subtitleUrl).toBe(`${DELIVERY}/${prefix}/subtitles.vtt`)
    })

    it('never produces a URL outside the attempt prefix', () => {
      for (const url of [parsed.hlsUrl, parsed.thumbnailUrl, parsed.subtitleUrl]) {
        expect(url?.startsWith(`${DELIVERY}/${prefix}/`)).toBe(true)
      }
    })

    it('is not double-prefixed when the API also has the Modal prefix', () => {
      // Applying the Modal layout on top of the agent's relative paths would
      // produce `videos/<id>/videos/<id>/attempts/...`, which exists nowhere.
      expect(parsed.hlsUrl).not.toContain(`videos/${fixtures.meta.videoId}/videos/`)
    })
  })

  describe('the two shapes differ only by prefix', () => {
    it('produces the same playback filename in both layouts', () => {
      const modal = parseCompletionPayload(fixtures.modal, {
        outputPrefix: null,
        deliveryBaseUrl: DELIVERY,
      })
      const agent = parseCompletionPayload(fixtures.agent, {
        outputPrefix: attemptPrefix(fixtures.meta.videoId, fixtures.meta.attemptId),
        deliveryBaseUrl: DELIVERY,
      })
      expect(modal.hlsUrl?.endsWith('/playlist.m3u8')).toBe(true)
      expect(agent.hlsUrl?.endsWith('/playlist.m3u8')).toBe(true)
      expect(modal.hlsUrl).not.toBe(agent.hlsUrl)
    })
  })
})
